<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class BookSeeder extends Seeder
{
    public function run(): void
    {
        DB::table('books')->insert([
            [
                'id'                 => 'b0000000-0000-0000-0000-000000000001',
                'title'              => 'Dom Quixote',
                'author'             => 'Miguel de Cervantes',
                'media'              => 'physical',
                'stock'              => 3,
                'digital_link'       => null,
                'reserved'           => false,
                'reserve_expiration' => null,
                'reserved_to'        => null,
                'fine'               => false,
                'created_at'         => '2026-01-05 10:00:00',
                'updated_at'         => '2026-01-05 10:00:00',
                'deleted_at'         => null,
            ],
            [
                'id'                 => 'b0000000-0000-0000-0000-000000000002',
                'title'              => 'O Senhor dos Anéis',
                'author'             => 'J.R.R. Tolkien',
                'media'              => 'physical',
                'stock'              => 2,
                'digital_link'       => null,
                'reserved'           => false,
                'reserve_expiration' => null,
                'reserved_to'        => null,
                'fine'               => false,
                'created_at'         => '2026-01-05 10:00:00',
                'updated_at'         => '2026-01-05 10:00:00',
                'deleted_at'         => null,
            ],
            [
                'id'                 => 'b0000000-0000-0000-0000-000000000003',
                'title'              => '1984',
                'author'             => 'George Orwell',
                'media'              => 'physical',
                'stock'              => 1,
                'digital_link'       => null,
                'reserved'           => true,
                'reserve_expiration' => '2026-05-31 23:59:59',
                'reserved_to'        => 'a0000000-0000-0000-0000-000000000004',
                'fine'               => false,
                'created_at'         => '2026-01-05 10:00:00',
                'updated_at'         => '2026-05-17 14:00:00',
                'deleted_at'         => null,
            ],
            [
                'id'                 => 'b0000000-0000-0000-0000-000000000004',
                'title'              => 'O Pequeno Príncipe',
                'author'             => 'Antoine de Saint-Exupéry',
                'media'              => 'physical',
                'stock'              => 5,
                'digital_link'       => null,
                'reserved'           => false,
                'reserve_expiration' => null,
                'reserved_to'        => null,
                'fine'               => false,
                'created_at'         => '2026-01-05 10:00:00',
                'updated_at'         => '2026-01-05 10:00:00',
                'deleted_at'         => null,
            ],
            [
                'id'                 => 'b0000000-0000-0000-0000-000000000005',
                'title'              => 'Crime e Castigo',
                'author'             => 'Fiódor Dostoiévski',
                'media'              => 'physical',
                'stock'              => 2,
                'digital_link'       => null,
                'reserved'           => false,
                'reserve_expiration' => null,
                'reserved_to'        => null,
                'fine'               => true,
                'created_at'         => '2026-01-05 10:00:00',
                'updated_at'         => '2026-05-10 09:00:00',
                'deleted_at'         => null,
            ],
            [
                'id'                 => 'b0000000-0000-0000-0000-000000000006',
                'title'              => 'Clean Code',
                'author'             => 'Robert C. Martin',
                'media'              => 'digital',
                'stock'              => null,
                'digital_link'       => 'https://biblioteca.com/digital/clean-code.pdf',
                'reserved'           => false,
                'reserve_expiration' => null,
                'reserved_to'        => null,
                'fine'               => false,
                'created_at'         => '2026-01-10 10:00:00',
                'updated_at'         => '2026-01-10 10:00:00',
                'deleted_at'         => null,
            ],
            [
                'id'                 => 'b0000000-0000-0000-0000-000000000007',
                'title'              => 'Design Patterns',
                'author'             => 'Gang of Four',
                'media'              => 'digital',
                'stock'              => null,
                'digital_link'       => 'https://biblioteca.com/digital/design-patterns.pdf',
                'reserved'           => false,
                'reserve_expiration' => null,
                'reserved_to'        => null,
                'fine'               => false,
                'created_at'         => '2026-01-10 10:00:00',
                'updated_at'         => '2026-01-10 10:00:00',
                'deleted_at'         => null,
            ],
            [
                'id'                 => 'b0000000-0000-0000-0000-000000000008',
                'title'              => 'The Pragmatic Programmer',
                'author'             => 'Andrew Hunt e David Thomas',
                'media'              => 'digital',
                'stock'              => null,
                'digital_link'       => 'https://biblioteca.com/digital/pragmatic-programmer.pdf',
                'reserved'           => false,
                'reserve_expiration' => null,
                'reserved_to'        => null,
                'fine'               => false,
                'created_at'         => '2026-01-10 10:00:00',
                'updated_at'         => '2026-01-10 10:00:00',
                'deleted_at'         => null,
            ],
        ]);
    }
}
